[project]
org-name = "ballerinax"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "java-nats-streaming"
    version = "2.2.3"
    path = "./lib/java-nats-streaming-2.2.3.jar"
    groupId = "io.nats"
    modules = ["nats"]

    [[platform.libraries]]
    artifactId = "jnats"
    version = "2.6.0"
    path = "./lib/jnats-2.6.0.jar"
    groupId = "io.nats"
    modules = ["nats"]

    [[platform.libraries]]
    artifactId = "protobuf-java"
    version = "3.9.1"
    path = "./lib/protobuf-java-3.9.1.jar"
    groupId = "com.google.protobuf"
    modules = ["nats"]
    
    [[platform.libraries]]
    artifactId = "nats"
    version = "1.0.0-SNAPSHOT"
    path = "../nats-native/build/libs/nats-native-1.0.0-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["nats"]
